author: taichangwei # 作者
description: taicw's blog
keyword: java, spring
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
# Projects: /project/
 About: /about/

# highlight
highlight: tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: taichangwei
gitment_repo: taichangwei.github.io
gitment_oauth_id: 775599adb3ad32ddb6df
gitment_oauth_secret: 4c6a01da9493c463ea9893ebcec29bc747ae40e9

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about:
  banner: /images/about_banner.jpg
  avatar: /images/avatar.png
  description: "True mastery of any skill takes a lifetime."
  weibo_username:
  twitter_username:
  github_username: taichangwei
  zhihu_username:
  douban_username:
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
